[package]
name = "mock-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["macros", "rt", "rt-multi-thread", "signal" ] }
clap = {version = "3.0.14", features = ["derive"]}
serde = "1.0.136"
serde_derive = "1.0.136"
tracing = "0.1"
tracing-subscriber = {version = "0.3.8", features = ["env-filter"]}
tracing-error = "0.2.0"
tracing-core = "0.1.21"
color-eyre = {version = "0.6.0", features = ["color-spantrace"]}
serde_json = "1.0.79"
execution_layer = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
types = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
task_executor = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
sensitive_url = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
eth2 = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
exit-future = "0.2.0"
parking_lot = "0.12.0"
hex = "0.4.3"
slog = "2.7.0"
sloggers = "2.1.1"
mev-build-rs = {git = "https://github.com/ralexstokes/mev-rs", rev = "a088806575805c00d63fa59c002abc5eb1dc7709"}
futures-channel = "0.3.21"
tracing-slog = "0.1.0"

[patch.crates-io]
eth2_serde_utils = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
eth2_ssz_types = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
tree_hash = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
eth2_ssz = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
eth2_hashing = { git = "https://github.com/realbigsean/lighthouse", rev = "3110786ded600cda837661756235eecdd4758716" }
