[package]
name = "mock-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["macros", "rt", "rt-multi-thread", "signal" ] }
clap = {version = "3.0.14", features = ["derive"]}
serde = "1.0.136"
serde_derive = "1.0.136"
warp = "0.3.2"
futures = "0.3.21"
tracing = "0.1"
tracing-subscriber = {version = "0.3.8", features = ["env-filter"]}
tracing-error = "0.2.0"
tracing-core = "0.1.21"
color-eyre = {version = "0.6.0", features = ["color-spantrace"]}
serde_json = "1.0.79"
execution_layer = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
types = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
task_executor = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
warp_utils = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
sensitive_url = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
exit-future = "0.2.0"
parking_lot = "0.12.0"
lru = "0.7.3"
hex = "0.4.3"

[patch.crates-io]
eth2_serde_utils = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_ssz_types = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
tree_hash = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_ssz = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
eth2_hashing = { git = "https://github.com/sigp/lighthouse", branch = "unstable" }
